# Generated by Django 4.0.1 on 2022-01-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadAccidentPoint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('geometry', models.JSONField(null=True)),
                ('properties', models.JSONField(null=True)),
                ('inwater', models.BooleanField()),
                ('coordinatesisaccurate', models.BooleanField()),
                ('inregion', models.JSONField(null=True)),
                ('onroad', models.BooleanField()),
                ('distancedif', models.CharField(max_length=100)),
                ('yandexgeocoder', models.JSONField(null=True)),
                ('adminlevel', models.JSONField(null=True)),
                ('dtptime', models.DateTimeField()),
                ('valid', models.BooleanField()),
                ('validpercent', models.IntegerField()),
            ],
        ),
    ]
